### ISSUE TITLE
Создать эндпоинт для dashboard

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#11]
В контроллере проекта сделать получение dashboard с учетом пагинации

Метод в контроллере получает id проекта:
POST: /api/project
payload: {"id": 123}

По этому id возвращается response вида (примерно):
![image](https://user-images.githubusercontent.com/42907301/213220825-792a8f09-3a20-471e-8940-9bfd41e8770b.png)

**Comment by VladisStep** [comment]
Пагинацию вынесу в отдельную таску
