### ISSUE TITLE
v0.5.0 Сделать assignee к таске

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#114]
Нужно создать новую колонку в таске assignee_id. В ней будет храниться то, кто является assignee к таске, т.е. кто будет ее выполнять

На данный момент assignee может менять любой юзер, у которого есть доступ к проекту. Assignee можно добавить, поменять на другого или вообще удалить (установить в null)

Также нужно добавить assigneeUserPic

Еще сейчас на фронт передается в TaskDto только id пользователя, надо обсудить и решить, будет ли фронт сам доставать user pic и тд, либо нужно еще передавать displayName (или firstName+lastName)

**Comment by Sabfes** [comment]
1. Асинье можно выбрать из списка людей в проекте. Тоесть нужен метод для получения всех людей в проекте.
2. Пока может менять любой юзер у которого есть доступ (в будущем возможно будет по правам)
3. ДикПик(юзер пик нужен)
4.1 передавать сразу ссылку на картинку (userPic)
4.2 Нужно все displayName нужн и firstName lastName, id, userPic, email в общем как и инфа о овнере
