### ISSUE TITLE
v0.5.0 Добавление юзера к проекту

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#115]
На фронте будет возможность добавлять юзера на проект. Как это будет происходить: с помощью инвайт ссылки или с помощью ввода никнейма пользователя и добавление его - пока непонятно, надо обсудить

- Нужно к сущности проекта добавить список айдишников пользователей, которые могут просматривать данный проект
- Пользователей из проекта можно удалять и добавлять новых
- Изменять пользователей на данный момент может только владелец проекта
- В рамках этой же задачи нужно продумать, как сделать, чтобы к определенному проекту имели доступ все, кто добавлены к нему. Потому что сейчас для каждого пользователя выдается список проектов только тех, которые он сам создал, т.е. где он является владельцем

**Comment by Sabfes** [comment]
1. вообще нужен инвайт по ссылке но и с помощью поиска на данном этапе, предлагаю оставить только по поиску, тк по инвайту займет много времени а профита хуй с крошкой.
Если по поиску то нужен метод поиска по всем юзерам (писал это в другой таске в этой версии), допустим ввожу sab - мне выпадают sabfes, sabmit, sabVanya и тд
2,пользователей может удалять только овнер (пока только такие роли, в будущем права доступа буду меняться как и роли)

**Comment by IvanShish** [comment]
- [ ] Эндпоинт для получение юзеров по фильтру. Пример самого часто используемого фильтра в данном случае:  `"[{"property":"displayName","operator":"LIKE","value":"user"}]"`
- [ ] Создать таблицу в БД и все соответствующие штуки для связи many to many между проектами и юзерами
- [ ] Добавить возможность добавлять и удалять юзеров в проекте

**Comment by IvanShish** [comment]
https://www.bezkoder.com/jpa-many-to-many/
https://www.baeldung.com/hibernate-initialize-proxy-exception
