### ISSUE TITLE
При запросе данных о пользователе нужно добавить всю инфу (как минимум его аватар)

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#128]
<img width="658" alt="image" src="https://github.com/FEBFES/FF-TM-BACK/assets/45693382/6986864f-da2a-43e0-a8e2-61b9dcc00269">
пока так

**Comment by IvanShish** [comment]
Нужно будет переделать UserEntity из таблицы во view, как это сделано с тасками, чтобы можно было легко доставать картинку пользователя из таблицы file_entity и выдавать путь до нее в UserDto
