### ISSUE TITLE
v0.6.0 Назначение ролей

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#134]
Нужно добавить возможность назначать определенные роли, при получении юзеров на каком-то проекте нужно также выводить роль юзера

**Comment by IvanShish** [comment]
А что вообще по ролям нужно сделать? Вот я создам 3 роли в таблице.
1. Нужен эндпоинт для получения ролей?
2. Возможности, которые есть у каждой роли, должны на бэке храниться? Или на фронте в зависимости от роли будет функционал ограничиваться и все. Я про то, что описано здесь: https://github.com/orgs/FEBFES/discussions/191 
3. Нужно при получении всех юзеров проекта, отправлять с бэка еще и роль каждого юзера?
4. То же самое, что и в 3 пункте, но при получении единичного юзера? По id, по фильтру и тд
5. Эндпоинт для смены роли у юзера? Нужно ли на бэке при этом делать проверку, что тот, кто меняет роль, обладает правом это делать (то есть этот юзер - owner)?

**Comment by Sabfes** [comment]
1 да нужен, буду при логине получать
2 и там и там тоесть я буду скрывать и тд но если гдет пройдет запрос ты на бэке должна ошибка быть 403
3 хз
4 хз

5 да нужно, и да проверка конечно нужна

**Comment by Sabfes** [comment]
пушто логин раз в 2 месяца у нас

**Comment by IvanShish** [comment]
1. А как owner будет роли назначать? Откуда ты их список получишь? Без хард кода если
2. Ну тогда еще наверное надо чтобы вместе с тасками тоже приходило, не? Вдруг пользователь выйдет, через месяц сразу зайдет на страницу с таской. И откуда мы роль возьмем?

**Comment by IvanShish** [comment]
https://thorben-janssen.com/ternary-associations/
https://www.baeldung.com/role-and-privilege-for-spring-security-registration
https://github.com/spring-projects/spring-security/issues/13188
