### ISSUE TITLE
v0.4.1  Фильтры переделать

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#152]
РАЗДЕЛЕНИЕ ФИЛЬТРОВ: & (амперсант)

url: dashboard?name='refactor'&type='refactor'&date='01.01.2023'&assignee=4

id=123 - EQ
name='taskName' - LIKE
description='Длинное описание таски бла бла бла' - LIKE
projectId='2' - EQ
columnId='3' - EQ
priority='low' - EQ
type='refactor' - EQ
owner=1 - EQ
assignee=3 - EQ

**Comment by IvanShish** [comment]
https://blog.tratif.com/2017/11/23/effective-restful-search-api-in-spring/

**Comment by IvanShish** [comment]
https://github.com/vladmihalcea/hypersistence-utils#hibernate-6 - для колонки типа priority
