### ISSUE TITLE
v0.4.1 Создать интерфейс/класс для преобразования списка в массив

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#157]
Есть два поля сейчас в TaskColumnEntity:
![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/9dc25f67-8fbb-42aa-b277-39b1e300c9d6)

Предлагаю создать интерфейс или класс, от которого будут наследоваться колонки, таски и проекты, так как туда нужен похожий функционал. Там будет создание как раз этих двух колонок, а также final метод, в котором будет преобразование из списка в массив.

Тогда 2 вопроса: 
1. Будем ли переименовывать поля, чтобы они везде были одинаковые (типа childNodeId), либо же сделаем так, чтобы каким-то образом эти имена для каждого класса задавались (типа методов setName, который каждый класс, имплементирующий созданный интерфейс должны будут определить, где и будет задаваться, к примеру, childTaskColumnId)
2. Интерфейс/класс/абстрактный класс?

**Comment by VladisStep** [comment]
1. Думаю стоит, чтобы можно было написать один сервис, который будет это обрабатывать 
2. Интерфейс, чтобы можно было множественное наследование использовать. По сути, можно будет добавить его к сущности и все. Но, возможно, я что-то упускаю

**Comment by VladisStep** [comment]
@IvanShish ар ю эгри?

**Comment by IvanShish** [comment]
Мне кажется, что лучше использовать массив для хранения порядка, а не список.
Потому что:
1. Плюс списка - легкое добавление. Но добавление у нас везде будет происходить в конец массива, а это не затратное действие
2. Плюс списка - легкое удаление. Проекты удаляться будут редко, колонки тоже. Таски могут побольше, но я бы вообще их делал не удаляемыми. Но в любом случае удаление будет происходить редко, поэтому это не так важно
3. А вот что будет происходить чаще всего - получение элемента/элементов. И тут попроще, как мне кажется, с массивом будет
4. Изменение порядка - надо будет как у списка менять указатели у обоих элементов, так и у массива просто поменять int order у элемента

**Comment by VladisStep** [comment]
1. Если добавляем в конце, то тогда разницы нет
2. Мне кажется, стоит удалять любые сущности. Иначе же нужно добавлять дополнительную колонку, в которой нужно отслеживать состояние таски (удалена или нет), фильтрацию по этой колонке добавлять в каждый запрос сущности. Короче лишний геморой. Насчет самого удаления есть сложность с изменением порядка в массиве(аналогично п4). В листе тоже есть сложности, но там их можно решить за одно обновление. 
3. Да, если у нас уже будет выставлен порядок, то лишние джойны или какие-то рекурсии придумывать не нужно
4. У списка мы берем два элемента и меняем у них следующий/предыдущий элемент. У массива мы обрабатываем разные случаи 
- Если мы перемещаем элемент c позиции n на позицию 1, то необходимо у всех элементов с 1 до n-1 прибавляем 1 к порядку
- Если мы перемещаем 1 на позицию n, то мы у элементов с 2 по n отнимаем 1
-  Вставки в середину. Тут больше описывать, но думаю и так понятно

По итогу сложно сказать, что является сложнее. Запариться с выводом или с добавлением/удалением/изменением
