### ISSUE TITLE
v0.9.0 Оптимизация методов с мемберами

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#158]
Вот эти 3 метода:
![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/9079c9dd-94f0-400d-b805-00c62a6550d5)

**Главное из обсуждения** отсюда: https://github.com/FEBFES/FF-TM-BACK/pull/154

В Projects есть поле `Set<UserEntity> members` , и проблема в том, что в UserEntity нет userPic. Он есть только в UserView. И в общем хз пока как лучше сделать. Если поменять `Set<UserEntity> members` на` Set<UserVIew> members`, то не думаю, что сработает, потому что UserView - read only. Как вариант добавить LAZY many to many связь, где помимо UserEntity будут мемберы из UserView, но как-то такое себе решение по-моему

UserEntity используется для добавления/изменения юзера, а UserView - только для получения

**Как вариант** еще можно попробовать следующее: в ProjectEntity поменять тип мемберов: с `Set<UserEntity>` на `Set<UserView>`, тогда мемберы будут только для чтения. А для добавления/удаления мембера создать еще один Entity для таблицы со связью проектов и юзеров под названием `ff-tm.public.user_project`. И уже используя этот entity делать добавление/удаление

**Comment by VladisStep** [comment]
Думаю, что в `ProjectEntity ` необходимо оставить `Set<UserEntity>` так как при изменении сущности в проекте и сохранении проекта, сущность будет сохранена. Так же в нашем случае `UserVIew` создавался для объединения всех полей, необходимых для отображения пользователя на клиенте и со стороны бэка он не особо полезен на данный момент

**Comment by IvanShish** [comment]
К этому же относится этот таск: https://github.com/FEBFES/FF-TM-BACK/issues/166

**Comment by IvanShish** [comment]
Ветка (если надо): [fixes/158/members-refactoring](https://github.com/FEBFES/FF-TM-BACK/tree/fixes/158/members-refactoring)

Надо подумать, можно ли сделать так, чтобы в ProjectEntity, при получении мемберов:
![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/d473e7cf-7274-4a61-ae6b-6b863175fa84)

это получение можно было сделать одним запросом. Поскольку сейчас есть роли на проекте у каждого юзера, то я хз как в UserView добавить еще и переменную String role с помощью Hibernate. Не знаю как это сделать, потому что этот параметр зависит от user_id и от project_id, и если user_id еще понятно как можно привязать, то project_id - нет. По идее, одним запросом на SQL должно выглядеть так:

```
SELECT u.*, (SELECT r.name FROM role r INNER JOIN project_user_role pur ON pur.role_id=r.id AND pur.user_id=u.id AND pur.project_id=?) FROM v_user u
```

Как раз единственный параметр, который нужно передавать в этот запрос - это project_id. 

В общем есть ли вариант как-то сделать, чтобы этот запрос посылался при получении мемберов на проекте или нет

**Comment by VladisStep** [comment]
Ну запрос вроде корректный, но я бы его вот так записал
```
SELECT u.*, r.name
FROM v_user u
INNER JOIN project_user_role pur ON pur.role_id=r.id AND pur.user_id=u.id
INNER JOIN role r ON pur.role_id=r.id
```

**Comment by IvanShish** [comment]
Используются проекции: https://thorben-janssen.com/spring-data-jpa-query-projections/#DTOs_as_Interfaces
