### ISSUE TITLE
прописать заголовок "Cache-control" на бэке

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#167]

**Comment by Sabfes** [comment]
As Evans mentioned this headers should be set from the server side. How you actually set the headers differs between backend programming languages/servers.

Here are a few examples:

-Node.js res.setHeader('Cache-Control', 'no-cache');
-Nginx add_header Cache-Control no-cache;

[Share](https://stackoverflow.com/a/67079750)
Follow

**Comment by IvanShish** [comment]
Нужно включить кэш на медиа

**Comment by IvanShish** [comment]
https://www.baeldung.com/spring-mvc-cache-headers

сделал 1 час
