### ISSUE TITLE
v0.9.0 Мелкие замечания по рефакторингу

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#179]

**Comment by IvanShish** [comment]
![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/fd26a9b9-eb6d-44a1-b7cb-f1c68a711938)

Есть SaveFileException. Мне кажется можно в данном случае выводить и IOException:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/4e142db5-0a14-41a5-8097-576a1db6ce09)

Потому что это в любом случае серверная ошибка, и по IOException будет понятно, что почему-то на сервере не получилось сохранить файл. Не уверен, что нам здесь нужно кастомное исключение в виде SaveFileException

**Comment by IvanShish** [comment]
### 2

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/d47f84bd-e4e7-4b3a-9260-8f95d887c911)

Здесь не вижу смысла приводить AuthenticationDto к UserEntity. В любом случае в методе authenticateUser в сервисе используется только логин и пароль:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/7c1a3d75-2631-4cd4-92f8-3ae5436fc099)

**Comment by IvanShish** [comment]
### 3

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/ce8ef2ee-ee3c-47dd-b819-779cb7e792b9)

Эти эндпоинты сейчас в ProjectController. Может создать MemberController?

**Comment by IvanShish** [comment]
### 4

Есть дублирование кода. UserView:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/5f81ecfc-a886-40ff-a764-ba38d332ca82)

UserEntity:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/e49d6ee1-4788-4735-9368-cdaee6840141)

Отличие в том, что у UserEntity колонки в базе в snake_case, а у UserView - в camelCase. Можем ли мы как-то общий User создать в таком случае?

**Comment by IvanShish** [comment]
### 5

Такая проблема в сонаре:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/6ed6ea77-35b1-4ae2-81eb-00440d146a38)

Если сделаю это поле transient, то пойдут ошибки, связанные с этим полем. Видимо, используется сериализация в jpa. Поменять Map на HashMap не могу - там используется PersistenceMap:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/0fa66973-e3ff-48f1-aacd-68904189053c)


Сделать PersistenceMap тоже не могу, появляется такая ошибка:

`org.springframework.orm.jpa.JpaSystemException: could not re-associate uninitialized transient collection`

**Comment by VladisStep** [comment]
1.  А нельзя наследовать SaveFileException от IOException? Все-таки в SaveFileException  выводилось название файла с которым проблемы

2. На первый взгляд это не выглядит чем-то неправильным (перобразуем модель, пришедшую с фронта, к нашей модели). В теории если добавлять другие методы авторизации, то лучше использовать юзера. Но тут авторизация только через логин и пароль. Я бы не стал это менять, так как особого смысла изменение не добавит. Ну или я чего-то важного не замечаю

3. А в контроллере проекта много методов? Если да и не удобно код читать, то стоит вынести в отдельный контроллер

4.  А нельзя все названия писать в camelCase? А зачем их объединять, они вроде служат для разных вещей?

5. А обязательно инициализировать?

**Comment by IvanShish** [comment]
1. Ну смотри, допустим при выбрасывании FileNotFoundException, который наследник IOException, пишется название файла: 
![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/38ad2c66-e1c9-4874-8188-966a2faf5919)
Да мне кажется и в других исключениях тоже пишется, так что нам необязательно оставлять кастомное исключение для этого случая
2. Важного ничего нет, просто можно убрать преобразование из AuthenticationDto в UserEntity :)
3. Да, там много эндпоинтов, по идее лучше бы вынести в отдельный контроллер. С другой стороны, я не знаю есть такой паттерн или нет, но везде же так делается, что существует сущность, к примеру, User. Соотственно должен быть UserEntity, UserRepository, UserService, UserController. А сущности, репозитория и сервиса для Member у нас нет, и как бы кажется, что не очень в таком случае делать MemberController. Что думаешь?)
4. Ну просто я привык, у меня так везде на проектах было, что в таблице пишется типа такого: FILE_NAME, а во вьюхе fileName. Поэтому и здесь так. Ну объединять - потому что сонар ругается на дублирование. А так да, можно сказать для разных вещей, просто колонки то одни и те же. С TaskEntity и TaskView похожая история, но там не так много одинаковых колонок
5. Имел ввиду сериализировать? Ну да, нужно, чтобы обязательно Serialazible был. Я не смотрел как там под капотом работает, но видимо сериализация каким-то образом там используется, потому что с transient не рабоает. Возможно серализация используется только вот в связах OneToMany и тд. Хз короче) Можно забить просто на эту ошибку

**Comment by VladisStep** [comment]
1. Наверное да, можно убрать

2. Если важно ничего нет, то пусть останется как есть

3. Думаю, норм создать отдельный контроллер. Тут мы просто разделяем ответственность для одной сущности.

4. Если просто сонар ругается, то пофиг. В данном случае у нас логика сложнее, чем он может проанализировать

5.  Можно и забить)
