### ISSUE TITLE
v0.9.0 Рефакторинг 

### ISSUE THREAD

**Issue by VladisStep** [FEBFES/FF-TM-BACK#187]
1. Вынести в enum
```
public static final List<String> DEFAULT_COLUMNS = List.of("BACKLOG", "IN PROGRESS", "REVIEW", "DONE");
``` 

2. В `ProjectManagementServiceImpl` подумать над переносом мапинга

3. Зарефакторить `ProjectMemberServiceImpl. getProjectForUser ` сделать более понятной строчку
```
ProjectWithMembersProjection project = projectRepository.getProjectByIdAndUserId(projectId, userId)
```

**Comment by VladisStep** [comment]
Причина рефакторинга https://github.com/FEBFES/FF-TM-BACK/pull/185

**Comment by VladisStep** [comment]
**Вопросы**

1. **Нужен ли `DashboardService`?** На данный момент в нем находится только один метод, который id проекта возвращает набор колонок с тасками. При условии, что мы выносим мапинг из сервисов, то метод, который возвращает колонки, логичнее пенести в `ColumnService`

**Comment by IvanShish** [comment]
Еще можно вынести в enum `DEFAULT_TASK_TYPES `в `TaskTypeServiceImpl`

**Comment by IvanShish** [comment]
1. Я 40 дней и 3 часа думал о том, нужен он или нет. Но если от него отказаться, то хз куда его сувать. В ProjectManagementService (кстати думал его назвать еще ProjectCRUDService, management мне не сильно нравится) хотелось как можно меньше методов оставить, поэтому туда не стал. А в остальные как-то по логике не подходит. Ну мб в ProjectMemberService. А вообще почему тебя DashboardService волнует, а DashboardController - нет? мммм??
Кстати еще из интересных фактов: `getProject` в  ProjectManagementService нигде не используется
MemberController можно переименовать в ProjectMemberController
Если у тебя есть идеи, как лучше организовать разделение сервисов для проекта, то пиши

2. И ты типа хочешь преобразовывать из dto в entity в контроллере? Нууууу типа тут такая же логика, как и в случае с возвратом entity, а не dto? Что мы можем допустим редактировать проект с помощью ProjectDto, а можем потом создать какое-то другое дто и надо будет еще один метод, принимающий другой параметр создавать? Мне кажется в каком-то другом сервисе мб это и имело бы место быть, нооооо хз короче, возможно это излишне. 
А в сам ProjectManagementServiceImpl же передается dto только в editProjectPartially? И там PatchDto, который никак не переделать в ProjectEntity же

**Comment by VladisStep** [comment]
> А вообще почему тебя DashboardService волнует, а DashboardController - нет? мммм??

Насчет DashboardController тоже согласен. Кажется что он тоже не нужен. Наверно у нас была идея, что дашборд будет отдельной сущностью со своими особенностями, но пока получается, что это набор колонок. Предлагаю пока не трогать, возьмемся за него, когда придумаем новый функционал  для дашборда

> Кстати еще из интересных фактов: getProject в ProjectManagementService нигде не используется

Используется в editProjectPartially

> MemberController можно переименовать в ProjectMemberController

Можно и так оставить, особо разницы нет

> Нууууу типа тут такая же логика, как и в случае с возвратом entity, а не dto?

Да, смысл всего этого, чтобы сервисы вообще не знали что такое dto 

> Что мы можем допустим редактировать проект с помощью ProjectDto, а можем потом создать какое-то другое дто и надо будет еще один метод, принимающий другой параметр создавать?

То есть для каждого дто мы будем создавать отдельный метод сервиса, который будет редактировать проект. Вот это звучит уже плохо. Моя идея иметь один метод, принимающий entity и работающий только с ней. А уже разные дто мапятся в entity

> А в сам ProjectManagementServiceImpl же передается dto только в editProjectPartially? И там PatchDto, который никак не переделать в ProjectEntity же

Да, согласен, что в данном случае лучше оставить так. Возможно просто постфикс dto не самый удачный. Например, необходимо будет, чтобы сервис обновлял поля проекта, и ему необходимо будет формировать dto для использования этого метода. Должен ли сервис формировать дто?
