### ISSUE TITLE
v1.2.0 Комментарии к таске

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#198]
К задаче должна быть возможность оставлять комментарии

Эндпоинты:
1. Получение комментариев. С сортировкой, чтобы по дате отправки можно было отсортировать. Насчет фильтрации пока хз надо ли
2. Создание комментария
3. Редактирование текста комментария с проверкой на то, что редактирует пользователь, который создал комментарий
4. Удаление комментария???

Вообще еще должна быть возможность добавить вложение в комментарий, но я хз как это реализовывать пока что) Мб просто ссылка какая то на файл, а фронт уже должен парсить

Есть чем дополнить?

**Comment by Sabfes** [comment]
1. фильтрация не нужна нужен эндпоинт по ид таски с сортировкой от старой к новой
пока без вложений
и можно без редактирования ну под вопросом

**Comment by IvanShish** [comment]
И комментарии должны быть не через вебсокеты реализованы, а как обычны сущности, да? Фронт будет подгружать новые комментарии по запросу?
