### ISSUE TITLE
Предложения по улучшению кода

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#52]

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216640427-886a6a78-88b0-4e12-b05e-41cd174497d4.png)
make final?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216640908-c3cee4e5-c45e-4108-873f-d44085488fee.png)
1 поменять на 2?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216641114-2f11b2b1-d0c1-4dcf-8339-7d6abf4164d1.png)
Поменять на лямбду?

**Comment by IvanShish** [comment]
Вопрос как лучше сделать: чтобы сервисы возвращали entity или dto?

**Comment by IvanShish** [comment]
Будем переименовывать все, что связано с колонкой (ColumnController, ColumnService, ...) на TaskColumnController и т.д.?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216642798-9f1e7eb0-4828-48d5-b19f-d41c90017453.png)
Очень важный вопрос: когда пишем путь к эндпоинту, ставить первым символом слэш или нет?) Чтобы было типа /v1/projects. Надо бы как-то привезти все к общему виду и может в ридми написать основные моментики, типа код стайла на нашем проекте

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216643093-dd250735-3b27-4c78-bda9-de63a1c3dc17.png)
Нужно ли, чтобы методы по редактированию и удалению что-нибудь возвращали?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216643336-119a8a55-2363-4deb-9f66-3b3dd0978782.png)
Выполнить TODO, написанный на скрине?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216643619-25221b3d-08a5-436c-8b06-cf4899c8aa30.png)
Еще вопрос по стилю: в каких случаях переносить на следующую строку аргументы, передаваемые в метод. К примеру, как тут. Здесь всего 2, и мне кажется они поместятся на одной строчке. А переносить стоит на следующую строку, если пересекает линию в идее, которая справа на скрине. Либо как лучше? И я думаю, что если переносить, то типа такого:
```
public void editProject(
            @PathVariable Long id,
            @RequestBody ProjectDto projectDto
    ) {
        projectService.editProject(id, projectDto);
    }
```

**Comment by IvanShish** [comment]
Вопрос по TaskController: как использовать projectId? Как использовать columnId во всех методах, кроме создания таски?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216644187-82550633-23ac-4749-9a57-7c7d108bee12.png)
Сделать в пагинации, чтобы page начинался с 0 или с 1?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216644304-772467fd-b6d2-4b24-b049-e2d982fdc854.png)
ProjectEntity: сделать name, чтобы он был nullable: false? И должен ли он быть уникальным? Ограничить name каким-то количеством символом и сделать то же самое для описания (description)?
То что в TODO как-то решаемо или нет?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216645158-a866d85d-1db4-4358-9b4f-2c179f9f8b81.png)
Здесь как-то много аннотаций. Они все нужны?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216645266-23fd4b8d-90d4-4426-acd7-59b58d7a5547.png)
Все DTO у нас имеют вид record. Что делать с этим ApiError? Может это и не DTO? Либо как-то сделать, чтобы он был record?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216646168-4486b0f6-843a-4698-a24d-03c56df83c3e.png)
Надо определиться с редактированием (всех entity касается). Редактируем только те поля, которые не null или все? В первом случае я так понимаю нельзя будет занулить какое-то поле, но можно это как-то продумать. Или оставляем так, что нужно полностью объект передавать, и мы все возможные поля меняем

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216646546-b99ca42d-1077-45b1-9120-7ca6039192eb.png)
Как лучше сделать удаление? Как на скрине или так, как это сделано в ProjectService и ColumnService?

**Comment by IvanShish** [comment]
![image](https://user-images.githubusercontent.com/42907301/216646653-715923cd-57a3-4afa-a959-5b6e69389f20.png)
Нужен ли такой метод? Он используется же только при создании новой колонки. Если нужен, то может переделать, чтобы все через builder было? Или и так норм

**Comment by IvanShish** [comment]
Будем ли добавлять логи в сервисы для колонок и проектов? Как это сделано в TaskService
![image](https://user-images.githubusercontent.com/42907301/216647158-e6b2e8f4-159c-4b95-a0b5-b9b68b6de728.png)

**Comment by VladisStep** [comment]
> Вопрос как лучше сделать: чтобы сервисы возвращали entity или dto?

лучше возвращает entity

> Вопрос по ColumnController: как использовать projectId при редактировании и удалении колонок?

оставим на будущее как есть 

> Будем переименовывать все, что связано с колонкой (ColumnController, ColumnService, ...) на TaskColumnController и т.д.?

Будем называть с Task

> ![image](https://user-images.githubusercontent.com/42907301/216642798-9f1e7eb0-4828-48d5-b19f-d41c90017453.png) Очень важный вопрос: когда пишем путь к эндпоинту, ставить первым символом слэш или нет?) Чтобы было типа /v1/projects. Надо бы как-то привезти все к общему виду и может в ридми написать основные моментики, типа код стайла на нашем проекте
 
Пишем без палочки как амигоскод




> ![image](https://user-images.githubusercontent.com/42907301/216643619-25221b3d-08a5-436c-8b06-cf4899c8aa30.png) Еще вопрос по стилю: в каких случаях переносить на следующую строку аргументы, передаваемые в метод. К примеру, как тут. Здесь всего 2, и мне кажется они поместятся на одной строчке. А переносить стоит на следующую строку, если пересекает линию в идее, которая справа на скрине. Либо как лучше? И я думаю, что если переносить, то типа такого:
> 
> ```
> public void editProject(
>             @PathVariable Long id,
>             @RequestBody ProjectDto projectDto
>     ) {
>         projectService.editProject(id, projectDto);
>     }
> ```

Вводим правила от двух и более переменных переносим на новую строку. как в примере

> ![image](https://user-images.githubusercontent.com/42907301/216645158-a866d85d-1db4-4358-9b4f-2c179f9f8b81.png) Здесь как-то много аннотаций. Они все нужны?

Надо разобраться

> ![image](https://user-images.githubusercontent.com/42907301/216645266-23fd4b8d-90d4-4426-acd7-59b58d7a5547.png) Все DTO у нас имеют вид record. Что делать с этим ApiError? Может это и не DTO? Либо как-то сделать, чтобы он был record?

Попробовать сделать рекорад. Если не работает, то найти решение
