### ISSUE TITLE
При создании нового проекта создавать сразу дефолтные колонки

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#59]
Как мы решили что при создании будут дефолтные колонки, думаю такие:

BACKLOG / RESEARCH / BUGS / IN PROGRESS / REVIEW / DONE 

ордеры сами решайте

@IvanShish, @VladisStep

**Comment by IvanShish** [comment]
Думаю достаточно BACKLOG, IN PROGRESS, REVIEW, DONE
Research, bugs - это тип задачи
