### ISSUE TITLE
v0.9.0 Сделать описание ошибок

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#67]
К примеру, сейчас кастомный exception EntityAlreadyExists выдает примерно такую ошибку: UserEntity already exists. Было бы неплохо переделать так, чтобы писалось примерно так: "A user with this email or login is already registered", то есть нормальная ошибка, так как она выводится потом на фронт
Перед тем, как это делать, нужно будет обсудить когда какие exception выбрасывать и что именно выводить

**Comment by VladisStep** [comment]
- так же сделать, чтобы выводился стектрейс в логи

**Comment by IvanShish** [comment]
Валидацию количества символов в названии, описании и других стринговых переменных

**Comment by IvanShish** [comment]
- EntityAlreadyExistsException - выбрасывается, когда уже существуют entity с определенными данными. На данный момент используется только для юзера. Стоит ли переименовывать в таком случае на UserAlreadyExistsException или он в теории может использоваться где-то еще?
TODO: unfinished

**Comment by IvanShish** [comment]
https://stackoverflow.com/questions/67290510/whether-all-error-messages-should-come-from-the-backend-in-a-form-that-can-be-sh

Для тех кто не знает английский (НО ЛУЧШЕ ПРОЧИТАТЬ ХОТЯ БЫ С ПЕРЕВОДЧИКОМ): 2 варианта есть. Сразу передавать сообщение ошибки с бэка на фронт. В таком случае на бэке нужно будет сделать, чтобы было типа такого ответа (так как у нас будут русский и английский на сайте):

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/d2030f95-f437-4bd6-8632-a5e897297d33)

Второй: бэк отсылает ответ в определенном виде, типа того, что ниже, а фронт интерпретирует его и трансформирует в легко читаемое юзером сообщение.

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/e8031139-93ad-4f67-bb37-b4f40d63f790)

Какой вариант будем делать мы?

**Comment by Sabfes** [comment]
так, пацанва слушаем и записываем:

0. шел нахер чел со стака
1. делаем по 2 варианту 
2. все вариации нужно определить и задокументировать в гите (сделать доку по ошибкам какая что и тд)
3. нужно отдельно продумать по логину и регистрации для безопасности (диплом писал по таким штукам и такая херь в owasp попадает, когда разрабы сами помогают хакать, если хотим по феншую то надо бы продумать)
4. VladisStep +rep
5. IvanShish -rep

**Comment by IvanShish** [comment]
https://www.toptal.com/java/spring-boot-rest-api-error-handling
