### ISSUE TITLE
Сделать метод для проверки токена юзера

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#74]
чтоб когда приложение открылось, фронт отправлял запрос isCheck(token) - и если просрочен то тротлил ошибку иначе 200 (в будущем при просроченном токене я буду делать запрос на рефреш токена)

**Comment by IvanShish** [comment]
JWT refresh: https://www.bezkoder.com/spring-boot-refresh-token-jwt/
