### ISSUE TITLE
v0.9.0 Рассмотреть необходимость заполнение связных полей через hibernate

### ISSUE THREAD

**Issue by VladisStep** [FEBFES/FF-TM-BACK#78]
В projectDto есть поле taskEntityList, которое хранить все задачи, связанные с проектом.
Почему стоит убрать это поле:
* При удалении проекта hibernate делает удаление каждой таски отдельным запросом, хотя это можно сделать одним запросом в базу
* При запросе проекта не всегда требуются его таски, поэтому нет смысла загружать задачки, когда они не нужны.

Необходимо подумать и переделать алгоритм получения задач для проекта.

Аналогичные поля есть в TaskColumnEntity. Там так же стоит рассмотреть использование taskEntityList

**Comment by IvanShish** [comment]
### 1. ProjectEntity: 

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/612db153-bf9f-4667-aaa9-44dfebb813bc)

taskEntityList - не нужен, можно удалить, так как нигде не используется. У нас нигде не требуется связь на данный момент между проектом - тасками. Все только через колонки (в том же дашбоарде таски лежат в колонках)

taskColumnEntityList - на самом деле сейчас тоже нигде не используется, потому что для этого появились projections: 

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/330340cc-c122-4e88-b048-3540657ed154)

В любом случае даже если бы они нужны были, то, наверное, их и правда стоило бы убрать. Потому что количество запросов, насколько я понимаю, не поменяется. Если мы добавим это поле, то будет запрос на проект и отдельный запрос на получение колонок. Если удалим это поле, то вручную будем получать колонки (ну в плане добавится строка с их получением, где они требуются). То есть при удалении этого поля увеличится только длина кода, и то не сильно. 

При этом при удалении проекта, нужно будет также самому вручную удалять колонки. Точнее сначала удалять колонки, а потом проект. Под вручную я подразумеваю взаимодействие с columnRepository. То есть ручное удаление - написание запроса на удаление в columnRepository и вызов этого метода. Ручное получение - по аналогии

### 2. TaskColumnEntity:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/5577922e-9161-4e66-acd2-efa8bc5d5dcc)

taskList - на самом деле сейчас тоже нигде не используется, поскольку таски могут фильтроваться, то их получение и так происходит в отдельном методе. Это еще касается этого issue: https://github.com/FEBFES/FF-TM-BACK/issues/113 

### 3. UserEntity:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/ad625437-0b6f-4d4a-8bfb-bd68eb23af49)

Здесь только одна "проблемная" переменная: projectRoles. Но кстати тут написано каскадное удаление. Я так понимаю при удалении юзера, удалится и связь в таблице project_user_role. То есть как ты и говорил, будет делаться несколько запросов на удаление. С другой стороны, будет ли у нас удаляться юзер? А если и будет, то наверняка очень редко. Так что возможно, из-за того что это не такое частое действие, а заменить я хз как (отдельный запрос каждый раз делать - такое), то я бы и так оставил

**Comment by VladisStep** [comment]
1. Ручное удаление не очень хорошо. Думаю, через liqubaise можно задать правила, чтобы при удалении проекта, колонки удалялись. Вроде еще можно на поле с колонками навесить lazy Initialization и тогда вроде лишних запросов не должно быть 

2. Тут тоже вопрос с удалением, при удалении проекта

3. Ну да, юзер удаляется редко. Но мне кажется он впринципе не удаляется, а делается не активным. Так что стоит ли вообще продумывать каскадное удаление в данном случае?

**Comment by IvanShish** [comment]
1. Да, on delete cascade надо будет сделать в БД, если не сделано сейчас
2. Ага
3. Ну да, лучше делать инактивным
