### ISSUE TITLE
v0.9.0 Подумать на какие поля в БД стоит добавить индексацию

### ISSUE THREAD

**Issue by IvanShish** [FEBFES/FF-TM-BACK#84]

**Comment by IvanShish** [comment]
Наверное INDEX для columnId в тасках, потому что по нему фильтрация происходит

**Comment by IvanShish** [comment]
### 1. Таблица favourite_project
![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/9d4127ac-7175-4fb5-bc26-6f353f1ee1d4)

Вариант единственный: индекс на project_id и на user_id. Ответ chat gpt на это предложение:

_Adding an index to project_id and user_id in the favourite_project table can improve the performance of the query, especially if the table contains a large number of records. The index will allow the database to quickly locate the relevant rows in the table, reducing the time required to execute the query._

_However, whether or not to add an index depends on various factors such as the size of the table, the frequency of the query, and the overall database performance. It is recommended to analyze the database performance using tools such as query profiling before deciding to add an index._

_Additionally, it is important to ensure that the query itself is optimized and uses appropriate join conditions and filtering criteria to minimize the amount of data that needs to be processed._

Использования этой таблицы в коде:

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/b72ddd2c-4afd-4f76-9d72-e57129848854)


То есть почти всегда она используется в джоине при получении проектов. Поэтому, возможно, было бы неплохой идеей поставить индекс туда. Но я не уверен, что эта таблица будет большой. Она будет точно <= таблице проектов. А проектов не так много, как тасок

**Comment by IvanShish** [comment]
Вообще по поводу добавления индексов на foreign keys еще есть статья эта: https://www.cybertec-postgresql.com/en/index-your-foreign-key/ 

![image](https://github.com/FEBFES/FF-TM-BACK/assets/42907301/2c005e33-42d1-4b0f-8350-561ba63156b6)

Вообще сложно оценить, насколько нам сейчас нужны индексы. Потому что база маленькая, записей мало. Сейчас они точно не нужны. Но мы же делаем, как правильно. С другой стороны, чтобы правильно расставить индексы, нужно смотреть разные метрики: как часто используется тот или иной запрос, сколько данных в базе. А все это оценить сейчас сложно

**Comment by VladisStep** [comment]
Согласен, что идексы нам не нужны. Вообще это тоже может быть опасной штукой, так как не все индексы полезны, а некоторые могут замедлить быстродействие. Думаю на индексы можно пока забить. Добавляются они не сложно, поэтому это не должно стать проблемой в будущем

**Comment by IvanShish** [comment]
Согласен
