### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#88]
Conts
expiryTimeAccess = '1 hour'
expiryTimeRefresh = '30 days'

Функционал

0. Регистрация ( request: formData;  response: null ),  
 - 200: клиент перенаправляет на пункт 1 (Логин)
 - 409 | 422: ошибка валидации, подсветка формы
 
1.  Логин ( request: formData; response: {new accessToken, new refreshToken })
 - 200: клиент перенаправляет на страницу проектов
 - 404 | 422: ошибка, подсветка формы 
2. Использование (request: any with accessToken , response: any)
 - 200: ok
 - 401 (истек аксес): клиент отправляет запрос на пункт 3 ( рефреш)
 - 403: Права доступа запрет
3. Рефреш (request: {refreshToken}; response: {new accessToken, new refreshToken})
4. Логаут?

_Originally posted by @Sabfes in https://github.com/FEBFES/FF-TM-FRONT/discussions/97#discussioncomment-5068369_

**Comment by IvanShish** [comment]
Получается что нужно сделать на бэке:
1. При регистрации ничего не возвращать
2. User id в базе с рефреш токеном сделать уникальным
3. При аутентификации происходит запрос в базу на получение рефреш токена. Если он есть/не валидный, то перезаписывается новым значением. Если нет, то генерируется новый
4. При рефреше нужно генерировать новый аксес токен и новый рефреш токен
5. Логаут удалить
