### ISSUE TITLE
Новые поля при создании тасок

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#94]
- [ ] Добавить поле при создании таски приоритет одно из 5 (low, medium, high, ivanUrgant, null)

- если нулл - значит приоритет не выбран
- если любое другое значение значит все ок
- при получении дашборда возвращать приоритет в тасках 

- [ ] Добавить поле тип при создании таски одно из 4 (пока) (bug, feature, research, question, дополните в комментарии)

- если нулл то не выбран
- если выбрали то его вернуть при получении дашборда с тасками
- может быть только 1 тип

**Comment by VladisStep** [comment]
https://www.baeldung.com/mapstruct-custom-mapper
