### ISSUE TITLE
v0.2.0 Переделать с базы в директорию и удалить эти методы

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#97]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/45693382/222504773-fef57222-7511-493e-a957-6a5e2bff5b11.png">

p.s (Ваня дурак не обдуманый)

**Comment by IvanShish** [comment]
Удалить эти два эндпоинта, картинку пользователя хранить не в базе, а в директории. В базе оставить ссылку на картинку. Картинка должна приходить на доску, а не только при получении данных пользователя
