### ISSUE TITLE
v0.3.0 Добавление файлов к таске

### ISSUE THREAD

**Issue by Sabfes** [FEBFES/FF-TM-BACK#98]

**Comment by IvanShish** [comment]
В рамках этой же задачи:
Создать таблицу в базе для приоритетов таски
Создать view для тасок
Создать enum для существующих сущностей, у которых могут быть вложения

**Comment by IvanShish** [comment]
https://stackoverflow.com/questions/41909388/multiple-file-upload-with-rest-assured

multiple files upload test
